// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

/*
All of these responses where generated by GPT using a prompt similar to:

```
Here's a JavaScript string literal template:

`I couldn't find a ${item} on your ${list} list.`

Create a JavaScript array with 7 variations of the template.
The variations should be helpful, creative, clever, and very friendly.
The variations should always use the back tick `` syntax.
The variations should always include ${item} and ${list} variables.
```

7 variations were asked for so that we can remove the 2 we like the least.
*/

export function getOnCallNotesInitialValue(): string {
    return (
        getRandomResponse([
            `Call Notes: 
            1 . Create a Sales Training Workshop. 
            2 . Segment Your Customer Base. 
            3 . Research Competitors and Market Trends. 
            4 . Develop Personalized Sales Pitches. 
            5 . Collaborate with Marketing.`,
        ]));
}


export function getPrepNotesInitialValue(): string {
    return (
        getRandomResponse([
            `Prep notes 
            1 . Item one in the list .
            2 . Item two in the list .
            3 . Item three in the list .`,
        ]));
}


/**
 * Responds when an unknown action is called
 * @param {string} action The action being performed
 * @returns {string} the response
 */
export function unknownAction(action: string): string {
    return getRandomResponse([
        `I'm sorry, I'm not sure how to ${action}.`,
        `I don't know the first thing about ${action}.`,
        `I'm not sure I'm the best person to help with ${action}.`,
        `I'm still learning about ${action}, but I'll try my best.`,
        `I'm afraid I'm not experienced enough with ${action}.`
    ]);
}

/**
 * Returns a string indicating that the bot cannot help with the current topic.
 * @returns {string} A string indicating that the bot cannot help with the current topic.
 */
export function offTopic(): string {
    return getRandomResponse([
        `I'm sorry, I'm not sure I can help you with that.`,
        `I'm sorry, I'm afraid I'm not allowed to talk about such things.`,
        `I'm sorry, I'm not sure I'm the right person to help you with that.`,
        `I wish I could help you with that, but it's not something I can talk about.`,
        `I'm sorry, I'm not allowed to discuss that topic.`
    ]);
}

/**
 * Returns a random response from an array of responses.
 * @param {string[]} responses - An array of string responses.
 * @returns {string} A random response from the array.
 */
function getRandomResponse(responses: string[]): string {
    const i = Math.floor(Math.random() * (responses.length - 1));
    return responses[i];
}
